apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  flightstats-app-id: <insert app ID>
  flightstats-app-key: <insert app key>
  tripit-api-key: <insert API key>
  tripit-api-secret: <insert API secret>
